package com.alura.forum.models.courses;

public enum Category {
    BACK_END_DEVELOPMENT,
    FRONT_END_DEVELOPMENT,
    DATA_SCIENCE,
    MACHINE_LEARNING,
    DATABASES,
    CLOUD_COMPUTING,
    DEVOPS,
    CYBER_SECURITY,
    PROJECT_MANAGEMENT,
    MOBILE_DEVELOPMENT
}
